// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api.Data;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240613182828_NewDataBase")]
    partial class NewDataBase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("api.Models.BrindeModel", b =>
                {
                    b.Property<int>("IdBrinde")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBrinde"));

                    b.Property<string>("Cadastro")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("DescricaoBrinde")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeBrinde")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<int>("Saldo")
                        .HasColumnType("int");

                    b.Property<DateTime>("Validade")
                        .HasColumnType("datetime2");

                    b.Property<int>("ValorEcopoints")
                        .HasColumnType("int");

                    b.HasKey("IdBrinde");

                    b.ToTable("TB_BRINDE");

                    b.HasData(
                        new
                        {
                            IdBrinde = 1,
                            Cadastro = "S",
                            DescricaoBrinde = "Caneca Ecológica",
                            NomeBrinde = "Caneca",
                            Quantidade = 100,
                            Saldo = 100,
                            Validade = new DateTime(2025, 6, 13, 15, 28, 27, 403, DateTimeKind.Local).AddTicks(9196),
                            ValorEcopoints = 150
                        },
                        new
                        {
                            IdBrinde = 2,
                            Cadastro = "S",
                            DescricaoBrinde = "Camiseta Reciclada",
                            NomeBrinde = "Camiseta",
                            Quantidade = 50,
                            Saldo = 50,
                            Validade = new DateTime(2025, 6, 13, 15, 28, 27, 403, DateTimeKind.Local).AddTicks(9208),
                            ValorEcopoints = 200
                        });
                });

            modelBuilder.Entity("api.Models.ColetaModel", b =>
                {
                    b.Property<int>("IdColeta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdColeta"));

                    b.Property<int>("CodigoEcoponto")
                        .HasColumnType("int");

                    b.Property<int>("CodigoUtilizador")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataColeta")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEcoponto")
                        .HasColumnType("int");

                    b.Property<int>("IdUtilizador")
                        .HasColumnType("int");

                    b.Property<double>("Peso")
                        .HasColumnType("float");

                    b.Property<string>("SituacaoColeta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("TotalEcopoints")
                        .HasColumnType("real");

                    b.HasKey("IdColeta");

                    b.ToTable("TB_COLETA");

                    b.HasData(
                        new
                        {
                            IdColeta = 1,
                            CodigoEcoponto = 1001,
                            CodigoUtilizador = 2001,
                            DataColeta = new DateTime(2024, 6, 13, 15, 28, 27, 403, DateTimeKind.Local).AddTicks(9040),
                            IdEcoponto = 1,
                            IdUtilizador = 1,
                            Peso = 15.5,
                            SituacaoColeta = "Completa",
                            TotalEcopoints = 50f
                        },
                        new
                        {
                            IdColeta = 2,
                            CodigoEcoponto = 1002,
                            CodigoUtilizador = 2002,
                            DataColeta = new DateTime(2024, 6, 13, 15, 28, 27, 403, DateTimeKind.Local).AddTicks(9058),
                            IdEcoponto = 2,
                            IdUtilizador = 2,
                            Peso = 20.0,
                            SituacaoColeta = "Pendente",
                            TotalEcopoints = 75f
                        });
                });

            modelBuilder.Entity("api.Models.EcopointsModel", b =>
                {
                    b.Property<int>("IdMaterial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMaterial"));

                    b.Property<int>("IdUtilizador")
                        .HasColumnType("int");

                    b.Property<string>("OrdemGrandeza")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<int>("TotalEcoPoints")
                        .HasColumnType("int");

                    b.HasKey("IdMaterial");

                    b.ToTable("TB_ECOPOINTS");

                    b.HasData(
                        new
                        {
                            IdMaterial = 1,
                            IdUtilizador = 1,
                            OrdemGrandeza = "A",
                            Quantidade = 10,
                            TotalEcoPoints = 0
                        },
                        new
                        {
                            IdMaterial = 2,
                            IdUtilizador = 2,
                            OrdemGrandeza = "B",
                            Quantidade = 20,
                            TotalEcoPoints = 0
                        });
                });

            modelBuilder.Entity("api.Models.EcopontoModel", b =>
                {
                    b.Property<int>("IdEcoponto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEcoponto"));

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CEP")
                        .HasColumnType("int");

                    b.Property<int>("CNPJ")
                        .HasColumnType("int");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Complemento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UF")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdEcoponto");

                    b.ToTable("TB_ECOPONTO");

                    b.HasData(
                        new
                        {
                            IdEcoponto = 1,
                            Bairro = "sla4",
                            CEP = 3081010,
                            CNPJ = 12345678,
                            Cidade = "sla5",
                            Complemento = "sla3",
                            Email = "ecoponto1@example.com",
                            Endereco = "sla2",
                            Latitude = 192.0,
                            Logradouro = "sla",
                            Longitude = 193.0,
                            Nome = "Ecoponto1",
                            PasswordHash = new byte[] { 173, 43, 174, 141, 219, 146, 59, 146, 26, 217, 58, 253, 53, 180, 79, 59, 26, 145, 209, 166, 57, 195, 226, 75, 43, 115, 102, 217, 21, 8, 121, 103, 196, 187, 162, 57, 56, 213, 111, 88, 109, 226, 124, 231, 137, 108, 212, 36, 222, 118, 172, 65, 68, 47, 34, 172, 241, 164, 18, 155, 118, 178, 11, 82 },
                            PasswordSalt = new byte[] { 117, 43, 242, 236, 225, 127, 114, 99, 253, 9, 43, 4, 79, 234, 20, 102, 136, 162, 31, 75, 36, 170, 125, 0, 209, 205, 66, 66, 21, 170, 98, 15, 152, 15, 50, 129, 90, 100, 4, 4, 232, 236, 21, 253, 232, 122, 146, 199, 49, 9, 103, 195, 222, 23, 67, 98, 231, 96, 2, 33, 179, 4, 130, 230, 91, 123, 233, 28, 118, 60, 98, 150, 124, 85, 86, 91, 122, 66, 242, 201, 181, 194, 217, 157, 74, 232, 112, 110, 1, 207, 68, 209, 33, 64, 1, 242, 202, 245, 83, 66, 237, 33, 165, 113, 67, 79, 127, 167, 253, 186, 85, 67, 7, 80, 188, 88, 24, 89, 144, 11, 68, 252, 151, 75, 10, 47, 14, 94 },
                            RazaoSocial = "Paz Mundial",
                            UF = "sl",
                            Username = "Ecoponto1"
                        },
                        new
                        {
                            IdEcoponto = 2,
                            Bairro = "sla4",
                            CEP = 3081010,
                            CNPJ = 12345678,
                            Cidade = "sla5",
                            Complemento = "sla3",
                            Email = "ecoponto2@example.com",
                            Endereco = "sla2",
                            Latitude = 192.0,
                            Logradouro = "sla",
                            Longitude = 193.0,
                            Nome = "Ecoponto2",
                            PasswordHash = new byte[] { 173, 43, 174, 141, 219, 146, 59, 146, 26, 217, 58, 253, 53, 180, 79, 59, 26, 145, 209, 166, 57, 195, 226, 75, 43, 115, 102, 217, 21, 8, 121, 103, 196, 187, 162, 57, 56, 213, 111, 88, 109, 226, 124, 231, 137, 108, 212, 36, 222, 118, 172, 65, 68, 47, 34, 172, 241, 164, 18, 155, 118, 178, 11, 82 },
                            PasswordSalt = new byte[] { 117, 43, 242, 236, 225, 127, 114, 99, 253, 9, 43, 4, 79, 234, 20, 102, 136, 162, 31, 75, 36, 170, 125, 0, 209, 205, 66, 66, 21, 170, 98, 15, 152, 15, 50, 129, 90, 100, 4, 4, 232, 236, 21, 253, 232, 122, 146, 199, 49, 9, 103, 195, 222, 23, 67, 98, 231, 96, 2, 33, 179, 4, 130, 230, 91, 123, 233, 28, 118, 60, 98, 150, 124, 85, 86, 91, 122, 66, 242, 201, 181, 194, 217, 157, 74, 232, 112, 110, 1, 207, 68, 209, 33, 64, 1, 242, 202, 245, 83, 66, 237, 33, 165, 113, 67, 79, 127, 167, 253, 186, 85, 67, 7, 80, 188, 88, 24, 89, 144, 11, 68, 252, 151, 75, 10, 47, 14, 94 },
                            RazaoSocial = "Paz Mundial",
                            UF = "sl",
                            Username = "Ecoponto2"
                        });
                });

            modelBuilder.Entity("api.Models.MateriaisModel", b =>
                {
                    b.Property<int>("IdMaterial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMaterial"));

                    b.Property<int>("Classe")
                        .HasColumnType("int");

                    b.Property<string>("DescricaoMaterial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdMaterial");

                    b.ToTable("TB_MATERIAIS");
                });

            modelBuilder.Entity("api.Models.UtilizadorModel", b =>
                {
                    b.Property<int>("IdUtilizador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUtilizador"));

                    b.Property<DateTime?>("DataAcesso")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("varbinary(max)");

                    b.Property<bool>("SituacaoEmail")
                        .HasColumnType("bit");

                    b.Property<int>("TotalEcoPoints")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUtilizador");

                    b.HasIndex("TotalEcoPoints")
                        .IsUnique();

                    b.ToTable("TB_UTILIZADOR");

                    b.HasData(
                        new
                        {
                            IdUtilizador = 1,
                            Email = "joao123@gmail.com",
                            Latitude = 0.0,
                            Longitude = 0.0,
                            Nome = "João",
                            PasswordHash = new byte[] { 173, 43, 174, 141, 219, 146, 59, 146, 26, 217, 58, 253, 53, 180, 79, 59, 26, 145, 209, 166, 57, 195, 226, 75, 43, 115, 102, 217, 21, 8, 121, 103, 196, 187, 162, 57, 56, 213, 111, 88, 109, 226, 124, 231, 137, 108, 212, 36, 222, 118, 172, 65, 68, 47, 34, 172, 241, 164, 18, 155, 118, 178, 11, 82 },
                            PasswordSalt = new byte[] { 117, 43, 242, 236, 225, 127, 114, 99, 253, 9, 43, 4, 79, 234, 20, 102, 136, 162, 31, 75, 36, 170, 125, 0, 209, 205, 66, 66, 21, 170, 98, 15, 152, 15, 50, 129, 90, 100, 4, 4, 232, 236, 21, 253, 232, 122, 146, 199, 49, 9, 103, 195, 222, 23, 67, 98, 231, 96, 2, 33, 179, 4, 130, 230, 91, 123, 233, 28, 118, 60, 98, 150, 124, 85, 86, 91, 122, 66, 242, 201, 181, 194, 217, 157, 74, 232, 112, 110, 1, 207, 68, 209, 33, 64, 1, 242, 202, 245, 83, 66, 237, 33, 165, 113, 67, 79, 127, 167, 253, 186, 85, 67, 7, 80, 188, 88, 24, 89, 144, 11, 68, 252, 151, 75, 10, 47, 14, 94 },
                            SituacaoEmail = true,
                            TotalEcoPoints = 100,
                            Username = "UsuarioJoao"
                        },
                        new
                        {
                            IdUtilizador = 2,
                            Email = "maria123@gmail.com",
                            Latitude = 0.0,
                            Longitude = 0.0,
                            Nome = "Maria",
                            PasswordHash = new byte[] { 173, 43, 174, 141, 219, 146, 59, 146, 26, 217, 58, 253, 53, 180, 79, 59, 26, 145, 209, 166, 57, 195, 226, 75, 43, 115, 102, 217, 21, 8, 121, 103, 196, 187, 162, 57, 56, 213, 111, 88, 109, 226, 124, 231, 137, 108, 212, 36, 222, 118, 172, 65, 68, 47, 34, 172, 241, 164, 18, 155, 118, 178, 11, 82 },
                            PasswordSalt = new byte[] { 117, 43, 242, 236, 225, 127, 114, 99, 253, 9, 43, 4, 79, 234, 20, 102, 136, 162, 31, 75, 36, 170, 125, 0, 209, 205, 66, 66, 21, 170, 98, 15, 152, 15, 50, 129, 90, 100, 4, 4, 232, 236, 21, 253, 232, 122, 146, 199, 49, 9, 103, 195, 222, 23, 67, 98, 231, 96, 2, 33, 179, 4, 130, 230, 91, 123, 233, 28, 118, 60, 98, 150, 124, 85, 86, 91, 122, 66, 242, 201, 181, 194, 217, 157, 74, 232, 112, 110, 1, 207, 68, 209, 33, 64, 1, 242, 202, 245, 83, 66, 237, 33, 165, 113, 67, 79, 127, 167, 253, 186, 85, 67, 7, 80, 188, 88, 24, 89, 144, 11, 68, 252, 151, 75, 10, 47, 14, 94 },
                            SituacaoEmail = true,
                            TotalEcoPoints = 100,
                            Username = "UsuarioMaria"
                        },
                        new
                        {
                            IdUtilizador = 3,
                            DataAcesso = new DateTime(2024, 6, 13, 15, 28, 27, 403, DateTimeKind.Local).AddTicks(9231),
                            Email = "admin@example.com",
                            Latitude = 0.0,
                            Longitude = 0.0,
                            Nome = "Admin",
                            PasswordHash = new byte[] { 173, 43, 174, 141, 219, 146, 59, 146, 26, 217, 58, 253, 53, 180, 79, 59, 26, 145, 209, 166, 57, 195, 226, 75, 43, 115, 102, 217, 21, 8, 121, 103, 196, 187, 162, 57, 56, 213, 111, 88, 109, 226, 124, 231, 137, 108, 212, 36, 222, 118, 172, 65, 68, 47, 34, 172, 241, 164, 18, 155, 118, 178, 11, 82 },
                            PasswordSalt = new byte[] { 117, 43, 242, 236, 225, 127, 114, 99, 253, 9, 43, 4, 79, 234, 20, 102, 136, 162, 31, 75, 36, 170, 125, 0, 209, 205, 66, 66, 21, 170, 98, 15, 152, 15, 50, 129, 90, 100, 4, 4, 232, 236, 21, 253, 232, 122, 146, 199, 49, 9, 103, 195, 222, 23, 67, 98, 231, 96, 2, 33, 179, 4, 130, 230, 91, 123, 233, 28, 118, 60, 98, 150, 124, 85, 86, 91, 122, 66, 242, 201, 181, 194, 217, 157, 74, 232, 112, 110, 1, 207, 68, 209, 33, 64, 1, 242, 202, 245, 83, 66, 237, 33, 165, 113, 67, 79, 127, 167, 253, 186, 85, 67, 7, 80, 188, 88, 24, 89, 144, 11, 68, 252, 151, 75, 10, 47, 14, 94 },
                            SituacaoEmail = true,
                            TotalEcoPoints = 0,
                            Username = "Admin"
                        });
                });

            modelBuilder.Entity("api.Models.UtilizadorModel", b =>
                {
                    b.HasOne("api.Models.EcopointsModel", "EcoPoints")
                        .WithOne("Utilizador")
                        .HasForeignKey("api.Models.UtilizadorModel", "TotalEcoPoints")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EcoPoints");
                });

            modelBuilder.Entity("api.Models.EcopointsModel", b =>
                {
                    b.Navigation("Utilizador")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
